#pragma once
#ifdef BUILDING_GENERATED_CODE
#define EXPORT_VAR __declspec(dllexport) extern
#define EXPORT_FUNC __declspec(dllexport)
#else
#define EXPORT_VAR __declspec(dllimport) extern
#define EXPORT_FUNC __declspec(dllimport)
#endif
// Standard C++ includes
#include <algorithm>
#include <chrono>
#include <iostream>
#include <random>

// Standard C includes
#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <intrin.h>

int inline gennCLZ(unsigned int value) {
    unsigned long leadingZero = 0;
    if( _BitScanReverse(&leadingZero, value)) {
        return 31 - leadingZero;
    }
    else {
        return 32;
    }
}

using std::min;
using std::max;
#define SCALAR_MIN 2.22507385850720138e-308
#define SCALAR_MAX 1.79769313486231571e+308
#define TIME_MIN 2.22507385850720138e-308
#define TIME_MAX 1.79769313486231571e+308
extern "C" {
// ------------------------------------------------------------------------
// global variables
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// timers
// ------------------------------------------------------------------------
EXPORT_VAR double initTime;
EXPORT_VAR double initSparseTime;
EXPORT_VAR double neuronUpdateTime;
EXPORT_VAR double presynapticUpdateTime;
EXPORT_VAR double postsynapticUpdateTime;
EXPORT_VAR double synapseDynamicsTime;
// Runner functions
EXPORT_FUNC void allocateMem();
EXPORT_FUNC void freeMem();
EXPORT_FUNC void stepTime(unsigned long long timestep, unsigned long long numRecordingTimesteps);

// Functions generated by backend
EXPORT_FUNC void updateNeurons(double t, unsigned int recordingTimestep); 
EXPORT_FUNC void updateSynapses(double t);
EXPORT_FUNC void initialize();
EXPORT_FUNC void initializeSparse();
EXPORT_FUNC void initializeHost();

// Merged group upload functions
EXPORT_FUNC void pushMergedNeuronInitGroup0ToDevice(unsigned int idx, double* V, double* W, double* v1, double* v2, double* v3, double* v4, double* w1, double* w2, double* w3, double* w4);
EXPORT_FUNC void pushMergedNeuronUpdateGroup0ToDevice(unsigned int idx, double* V, double* W, uint32_t* recordSpk, double* v1, double* v2, double* v3, double* v4, double* w1, double* w2, double* w3, double* w4);
}  // extern "C"
